### PR TITLE
Add PolkaGate Extension

### PR DESCRIPTION
**Pull request by AMIRKHANEF**
## Description
This pull request aims to add the PolkaGate extension to the Kappa Sigma Mu membership club website as a login option.

## Changes Proposed
- [x]  Integration of the PolkaGate extension as a login option.

## Motivation and Benefits
**Improved User Experience:** The addition of the PolkaGate extension will offer users an alternative and secure login method.

**Enhanced Accessibility:** It will make it easier for users of the Polkagate extension to engage with the Kappa Sigma Mu membership club website.

## Screenshots
image
image
image
image

### CODE REVIEW

**Review by laurogripa — APPROVED** [review]
Hey, @AMIRKHANEF! Thanks for submitting this PR, that's very thoughtful!

Ps.: I don't know if you are aware, but your bid of 0 KSM is still up and it's going to be accepted in 3 days and 12 hours, which means you'll become a candidate eligible to get a tattoo. I'm not sure if that's your intention, letting you know just in case 😃

**Review by laurogripa — CHANGES_REQUESTED** [review]
Oh, CI seems to be breaking because we are using an older version of Yarn.

I'll be OOO this next week, but I'll try to update Yarn in the next few weeks.

**Comment by AMIRKHANEF** [comment]
Hi @laurogripa,

Thanks for reviewing this PR! Enjoy your time out of the office, and next week works perfectly.

Regarding the tattoo, my apologies—I didn't realize such a small bid would actually go through. Thanks for the heads-up! I'll make sure to withdraw the bid before it gets accepted, as that wasn’t my intention.

**Comment by AMIRKHANEF** [comment]
As you can see, I upgraded the "@talismn/connect-wallets" to 1.2.5, which requires a newer version of Yarn. To address this, I went ahead and updated Yarn as well.

**Comment by laurogripa** [comment]
> As you can see, I upgraded the "@talismn/connect-wallets" to 1.2.5, which requires a newer version of Yarn. To address this, I went ahead and updated Yarn as well.

@AMIRKHANEF Yeah, I just had to update Yarn on CI too. Now it's working!

But I'm getting a weird behavior: I don't have any accounts imported on my PolkaGate extensions, but the selector lists my Talisman account as a possible choice for PolkaGate.

image

It also happens if I connect an account from Polkadot.js. Same issue. Apparently, the account selector lists the accounts from the last selected wallet instead of PolkaGate.

Can you take a look at this issue? You can use chopsticks if you need to test any signed extrinsic, the instructions are in the README file.

If not, I'll take a look later this week.

**Comment by AMIRKHANEF** [comment]
Hey @laurogripa, thanks for pointing this out!

The issue you encountered happens because PolkaGate handles account selection differently compared to other wallets when no account is selected for interacting with a DApp.
This caused some confusion with the `@talismn/connect-wallets`. 
We've addressed the problem, and it should be fixed in the next release. I'll keep you posted as soon as the new version is out so you can give it a try.

Thanks again for your help!

**Comment by laurogripa** [comment]
@AMIRKHANEF Ok, great!

I'll leave this open until the next release, so we can update the version and ship it!

**Comment by laurogripa** [comment]
@AMIRKHANEF All good now, working great!

Thanks again for your contribution! ❤️

**Review by laurogripa — APPROVED** [review]

**Pull request merged**
